export const ADD_PDF_REQUEST = "ADD_PDF_REQUEST";
export const ADD_PDF_SUCCESS = "ADD_PDF_SUCCESS";
export const ADD_PDF_FAILURE = "ADD_PDF_FAILURE";

export const FETCH_PDF_SUCCESS = "FETCH_PDF_SUCCESS";
export const FETCH_PDF_REQUEST = "FETCH_PDF_REQUEST";
export const FETCH_PDF_FAILURE = "FETCH_PDF_FAILURE";

export const DELETE_PDF_REQUEST = "DELETE_PDF_REQUEST";
export const DELETE_PDF_SUCCESS = "DELETE_PDF_SUCCESS";
export const DELETE_PDF_FAILURE = "DELETE_PDF_FAILURE";

export const UPDATE_PDF_REQUEST = "UPDATE_PDF_REQUEST";
export const UPDATE_PDF_SUCCESS = "UPDATE_PDF_SUCCESS";
export const UPDATE_PDF_FAILURE = "UPDATE_PDF_FAILURE";