###
GET http://localhost:8000/api/v1/auth/checkAuth
Authorization:Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmY0MmY2ZmQ3MWMyOTZkYzY2Mjg5OCIsIm5hbWUiOiJ0dXJvbGllbiIsImVtYWlsIjoia2Fzb25nb2tha3VtYmlndXlAZ21haWwuY29tIiwiaWF0IjoxNzE0OTk0MzQzLCJleHAiOjE3MTQ5OTQzODh9.ySQNOqkQfRWqbXRoiOcE3jqfJRlXAGjYvtt37GADYs8

###
POST http://localhost:8000/api/v1/auth/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmY0MmY2ZmQ3MWMyOTZkYzY2Mjg5OCIsIm5hbWUiOiJ0dXJvbGllbiIsImVtYWlsIjoia2Fzb25nb2tha3VtYmlndXlAZ21haWwuY29tIiwiaWF0IjoxNzE0OTk0MzQzLCJleHAiOjE3MTUwODA3NDN9.Mx35kNdSZ2IefHwxOoV8Chr7NbW05NxSt3Mw-yzLj4U"
}
###
DELETE http://localhost:8000/api/v1/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmY0MmY2ZmQ3MWMyOTZkYzY2Mjg5OCIsIm5hbWUiOiJ0dXJvbGllbiIsImVtYWlsIjoia2Fzb25nb2tha3VtYmlndXlAZ21haWwuY29tIiwiaWF0IjoxNzE0OTk5NzkwLCJleHAiOjE3MTUwODYxOTB9.WxYGvHGfXeXjWa-mW92Va63k-T_rZIA-j1vWmgL8O38"
}
###
POST http://localhost:8000/api/v1/auth/login
Content-Type:application/json

{
    "email":"kasongokakumbiguy@gmail.com",
    "password":"Turolien"
}