export const ADD_SOCIAL_REQUEST = "ADD_SOCIAL_REQUEST";
export const ADD_SOCIAL_SUCCESS = "ADD_SOCIAL_SUCCESS";
export const ADD_SOCIAL_FAILURE = "ADD_SOCIAL_FAILURE";

export const FETCH_SOCIAL_SUCCESS = "FETCH_SOCIAL_SUCCESS";
export const FETCH_SOCIAL_REQUEST = "FETCH_SOCIAL_REQUEST";
export const FETCH_SOCIAL_FAILURE = "FETCH_SOCIAL_FAILURE";

export const DELETE_SOCIAL_REQUEST = "DELETE_SOCIAL_REQUEST";
export const DELETE_SOCIAL_SUCCESS = "DELETE_SOCIAL_SUCCESS";
export const DELETE_SOCIAL_FAILURE = "DELETE_SOCIAL_FAILURE";

export const UPDATE_SOCIAL_REQUEST = "UPDATE_SOCIAL_REQUEST";
export const UPDATE_SOCIAL_SUCCESS = "UPDATE_SOCIAL_SUCCESS";
export const UPDATE_SOCIAL_FAILURE = "UPDATE_SOCIAL_FAILURE";