export const ADD_TESTIMONIALS_REQUEST = "ADD_TESTIMONIALS_REQUEST";
export const ADD_TESTIMONIALS_SUCCESS = "ADD_TESTIMONIALS_SUCCESS";
export const ADD_TESTIMONIALS_FAILURE = "ADD_TESTIMONIALS_FAILURE";

export const FETCH_TESTIMONIALS_SUCCESS = "FETCH_TESTIMONIALS_SUCCESS";
export const FETCH_TESTIMONIALS_REQUEST = "FETCH_TESTIMONIALS_REQUEST";
export const FETCH_TESTIMONIALS_FAILURE = "FETCH_TESTIMONIALS_FAILURE";

export const DELETE_TESTIMONIALS_REQUEST = "DELETE_TESTIMONIALS_REQUEST";
export const DELETE_TESTIMONIALS_SUCCESS = "DELETE_TESTIMONIALS_SUCCESS";
export const DELETE_TESTIMONIALS_FAILURE = "DELETE_TESTIMONIALS_FAILURE";

export const UPDATE_TESTIMONIALS_REQUEST = "UPDATE_TESTIMONIALS_REQUEST";
export const UPDATE_TESTIMONIALS_SUCCESS = "UPDATE_TESTIMONIALS_SUCCESS";
export const UPDATE_TESTIMONIALS_FAILURE = "UPDATE_TESTIMONIALS_FAILURE";