export const ADD_ME_REQUEST = "ADD_ME_REQUEST";
export const ADD_ME_SUCCESS = "ADD_ME_SUCCESS";
export const ADD_ME_FAILURE = "ADD_ME_FAILURE";

export const FETCH_ME_SUCCESS = "FETCH_ME_SUCCESS";
export const FETCH_ME_REQUEST = "FETCH_ME_REQUEST";
export const FETCH_ME_FAILURE = "FETCH_ME_FAILURE";

export const DELETE_ME_REQUEST = "DELETE_ME_REQUEST";
export const DELETE_ME_SUCCESS = "DELETE_ME_SUCCESS";
export const DELETE_ME_FAILURE = "DELETE_ME_FAILURE";

export const UPDATE_ME_REQUEST = "UPDATE_ME_REQUEST";
export const UPDATE_ME_SUCCESS = "UPDATE_ME_SUCCESS";
export const UPDATE_ME_FAILURE = "UPDATE_ME_FAILURE";